name: Docker CI/CD

on:
  push:
    branches: [ "main", "master" ] # Qaysi branchga push bo'lganda ishlashi
  pull_request:
    branches: [ "main", "master" ]

jobs:
  test-and-build:
    runs-on: ubuntu-latest

    steps:
    - name: Kodni yuklab olish
      uses: actions/checkout@v3

    - name: .env faylini yaratish (Secrets dan)
      run: |
        echo "TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}" >> .env
        echo "CHAT_ID=${{ secrets.CHAT_ID }}" >> .env

    - name: Docker Image Build qilish
      run: |
        docker build -t system-monitor:latest .
    - name: Konteynerni test qilish (Sog'lomligini tekshirish)
      run: |
        # 1. Konteynerni orqa fonda ishga tushiramiz
        docker run -d --name test-monitor -p 8000:8000 system-monitor:latest
        
        # 2. 10 soniya kutamiz (dastur to'liq yonishi uchun)
        sleep 10
        
        # 3. ENG MUHIMI: Konteyner ichidagi Python xatolarini logga chiqaramiz
        docker logs test-container
        
        # 4. Konteyner hali ham tirikmi yoki o'lganmi tekshiramiz
        docker ps -a
        
        # 5. Curl so'rovini yuboramiz
        curl -v http://localhost:8000/metrics || exit 1
    - name: Build muvaffaqiyatli xabari
      run: echo "Tabriklaymiz! Docker Image muvaffaqiyatli build bo'ldi va testdan o'tdi."